Repository coders-school/car-dashboard, pull requests merged in 2024-04, with the labels that each got.

#23 Add cppcheck target for cmake
  CMakeLists.txt
  cmake/cppcheck.cmake
Labels: Standard, Auto-closed

#24 Clang tidy
  .clang-tidy
  CMakeLists.txt
  cmake/clang-tidy.cmake
Labels: Standard

#25 Main repair adding layouts
  content/App.qml
  content/Car3D.qml
  content/Gauges.qml
  content/MainScreeen.ui.qml
  content/MenuButton.qml
  content/MusicPlayer.qml
  content/Navigation.qml
  content/PhoneList.qml
  imports/CarDashboard/Constants.qml
Labels: Standard

#50 New Features
  .clang-format
  .clang-tidy
  App.qmlproject-test
  CMakeLists.txt
  cmake/clang-format.cmake
  cmake/clang-tidy.cmake
  cmake/cppcheck.cmake
  cmake/files.cmake
  content/AirCondition.qml
  content/AirConditionSitControl.qml
  content/App.qml
  content/CMakeLists.txt
  content/Car3D.qml
  content/FuelLevel.ui.qml
  content/FuelLevel_EngineTemp/Main.svg
  content/FuelLevel_EngineTemp/PetrolNormalState.svg
  content/FuelLevel_EngineTemp/PetrolReserve.svg
  content/FuelLevel_EngineTemp/linia1.svg
  content/FuelLevel_EngineTemp/linia1_orange.svg
  content/FuelLevel_EngineTemp/linia2.svg
  content/FuelLevel_EngineTemp/linia3.svg
  content/FuelLevel_EngineTemp/linia4.svg
  content/FuelLevel_EngineTemp/linia5.svg
  content/FuelLevel_EngineTemp/linia6.svg
  content/FuelLevel_EngineTemp/linia6_red.svg
  content/FuelLevel_EngineTemp/liniaPrzerywana.svg
  content/FuelLevel_EngineTemp/otok.svg
  content/Gauges.qml
  content/MainBackground.ui.qml
  content/MainBackground/MainBackground.svg
  content/MainScreeen.ui.qml
  content/MenuButton.qml
  content/MusicPlayer.qml
  content/Navigation.qml
  content/PhoneList.qml
  content/SpeedGauge.ui.qml
  content/SpeedGaugePicture/MainBackground.svg
  content/SpeedGaugePicture/SmallBackgroundSpedometer.svg
  imports/CarDashboard/Constants.qml
  imports/CarDashboard/qmldir
  qmlmodules
  src/app_environment.h
  src/import_qml_components_plugins.h
  src/main.cpp
  utest/CMakeLists.txt
  utest/example_test.cpp
  utest/main.cpp
Labels: Unknown user

#57 Erase anchors in App.qml and MenuButton.qml adding in MenuButton clas…
  content/App.qml
  content/MenuButton.qml
Labels: Standard

#54 Fix unit test
  utest/CMakeLists.txt
Labels: Standard, Auto-closed

#62 Fix unit test
  utest/CMakeLists.txt
Labels: Standard

#55 Air condition controller
  content/AirCondition.qml
  src/airCondition/Controller.cpp
  src/airCondition/Controller.hpp
  src/main.cpp
  utest/SignalTester.hpp
  utest/airCondition/Controller_test.cpp
Labels: Standard, Auto-closed
